<?php

return [
    'hosteleria' => [
        'etiqueta' => 'Hostelería',
        'prioridad' => 10,
        'plantilla' => 'hosteleria',
        'tags' => [
            ['amenity', 'restaurant'], ['amenity', 'cafe'], ['amenity', 'bar'],
            ['amenity', 'pub'], ['amenity', 'fast_food'], ['amenity', 'ice_cream'],
            ['tourism', 'hotel'], ['tourism', 'guest_house'], ['tourism', 'apartment'],
            ['tourism', 'hostel'], ['tourism', 'motel'],
        ],
        'schema' => ['Restaurant', 'CafeOrCoffeeShop', 'BarOrPub', 'FastFoodRestaurant',
            'Hotel', 'LodgingBusiness', 'FoodEstablishment', 'Bakery'],
    ],
    'salud' => [
        'etiqueta' => 'Salud',
        'prioridad' => 20,
        'plantilla' => 'salud',
        'tags' => [
            ['amenity', 'clinic'], ['amenity', 'dentist'], ['amenity', 'dentists'],
            ['amenity', 'doctors'], ['amenity', 'veterinary'], ['amenity', 'pharmacy'],
            ['shop', 'optician'], ['shop', 'hearing_aids'],
            ['healthcare', 'physiotherapist'], ['healthcare', 'psychotherapist'],
        ],
        'schema' => ['Dentist', 'Physician', 'MedicalClinic', 'Optician',
            'VeterinaryCare', 'Pharmacy', 'MedicalBusiness', 'Hospital'],
    ],
    'retail' => [
        'etiqueta' => 'Comercio',
        'prioridad' => 30,
        'plantilla' => 'retail',
        'tags' => [
            ['shop', 'jewelry'], ['shop', 'clothes'], ['shop', 'shoes'],
            ['shop', 'fashion_accessories'], ['shop', 'furniture'],
            ['shop', 'interior_decoration'], ['shop', 'kitchen'],
            ['shop', 'electronics'], ['shop', 'computer'], ['shop', 'florist'],
            ['shop', 'cosmetics'], ['shop', 'perfumery'], ['shop', 'bicycle'],
            ['shop', 'sports'], ['shop', 'toys'], ['shop', 'books'], ['shop', 'pet'],
            ['shop', 'gift'], ['shop', 'deli'], ['shop', 'butcher'],
            ['shop', 'bakery'], ['shop', 'wine'], ['shop', 'musical_instrument'],
            ['shop', 'art'],
        ],
        'schema' => ['Store', 'ClothingStore', 'JewelryStore', 'ShoeStore',
            'FurnitureStore', 'OnlineStore', 'ShoppingCenter', 'BookStore',
            'PetStore', 'FloristShop', 'ElectronicsStore'],
    ],
    'servicios_profesionales' => [
        'etiqueta' => 'Servicios profesionales',
        'prioridad' => 40,
        'plantilla' => 'servicios',
        'tags' => [
            ['office', 'lawyer'], ['office', 'accountant'], ['office', 'notary'],
            ['office', 'insurance'], ['office', 'financial'], ['office', 'estate_agent'],
            ['office', 'architect'], ['office', 'tax_advisor'],
            ['office', 'employment_agency'], ['office', 'engineer'], ['office', 'surveyor'],
        ],
        'schema' => ['Attorney', 'LegalService', 'AccountingService', 'InsuranceAgency',
            'RealEstateAgent', 'Notary', 'ArchitectService', 'FinancialService',
            'EmploymentAgency'],
    ],
    'oficios' => [
        'etiqueta' => 'Oficios',
        'prioridad' => 50,
        'plantilla' => 'oficios',
        'tags' => [
            ['craft', 'carpenter'], ['craft', 'electrician'], ['craft', 'plumber'],
            ['craft', 'painter'], ['craft', 'roofer'], ['craft', 'locksmith'],
            ['craft', 'gardener'], ['craft', 'builder'], ['craft', 'hvac'],
            ['craft', 'glaziery'], ['craft', 'metal_construction'],
            ['shop', 'doityourself'], ['shop', 'hardware'],
        ],
        'schema' => ['HomeAndConstructionBusiness', 'Plumber', 'Electrician',
            'GeneralContractor', 'HVACBusiness', 'Locksmith',
            'RoofingContractor', 'HousePainter', 'MovingCompany'],
    ],
    'belleza' => [
        'etiqueta' => 'Belleza y bienestar',
        'prioridad' => 60,
        'plantilla' => 'belleza',
        'tags' => [
            ['shop', 'hairdresser'], ['shop', 'beauty'], ['shop', 'massage'],
            ['shop', 'nail_salon'], ['shop', 'tattoo'], ['amenity', 'spa'],
            ['leisure', 'fitness_centre'], ['leisure', 'sports_centre'],
        ],
        'schema' => ['BeautySalon', 'HairSalon', 'DaySpa', 'NailSalon', 'HealthClub',
            'TattooParlor', 'SportsActivityLocation'],
    ],
    'agencias' => [
        'etiqueta' => 'Agencias',
        'prioridad' => 70,
        'plantilla' => 'agencias',
        'tags' => [
            ['office', 'advertising_agency'], ['office', 'marketing'],
            ['office', 'advertising'], ['office', 'graphic_design'],
            ['office', 'web_design'], ['office', 'design'], ['office', 'it'],
            ['office', 'software'], ['office', 'telecommunication'],
            ['office', 'consulting'], ['office', 'company'],
            ['shop', 'advertising_agency'], ['craft', 'photographer'],
            ['craft', 'designer'],
        ],
        'schema' => ['AdvertisingAgency', 'MarketingAgency', 'WebDesignBusiness',
            'ProfessionalService'],
    ],
];
